name: Build Python Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  actions: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact_name: python-package
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel build

      - name: Build package
        run: |
          # Create setup.py
          cat <<EOF > setup.py
          from setuptools import setup, find_packages

          setup(
              name="github_action_package",
              version="0.1.0",
              packages=find_packages(),
              description="A simple example package",
              author="Aryan Gupta",
              author_email="aryangupta16082003@gmail.com",
          )
          EOF

          python3 -m build  # Creates the package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-package
          path: dist/
          if-no-files-found: error
          retention-days: 5
